import { User, Poem, Category, Comment, Collection, AudioTrack, Achievement, ActivityLog, Story, Quote } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-id',
    name: 'Administrator',
    email: 'admin@siragii.com',
    username: 'admin',
    role: 'admin',
    followersCount: 25,
    followingCount: 5,
    createdAt: '2026-01-15T00:00:00Z',
  }
];

export const mockCategories: Category[] = [
  { id: 'cat-love', name: 'Love', nameTa: 'காதல்', slug: 'love', description: 'Love and romance poetry.', descriptionTa: 'காதல் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600', poemsCount: 18 },
  { id: 'cat-breakup', name: 'Breakup', nameTa: 'பிரிவு', slug: 'breakup', description: 'Breakup and separation poems.', descriptionTa: 'பிரிவு கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600', poemsCount: 10 },
  { id: 'cat-motivation', name: 'Motivation', nameTa: 'ஊக்கம்', slug: 'motivation', description: 'Motivational and inspirational stanzas.', descriptionTa: 'ஊக்கமூட்டும் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600', poemsCount: 14 },
  { id: 'cat-friendship', name: 'Friendship', nameTa: 'நட்பு', slug: 'friendship', description: 'Celebrating bonds and friendships.', descriptionTa: 'நட்புக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600', poemsCount: 12 },
  { id: 'cat-life', name: 'Life', nameTa: 'வாழ்க்கை', slug: 'life', description: 'Reflections on the journey of life.', descriptionTa: 'வாழ்க்கைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600', poemsCount: 16 },
  { id: 'cat-family', name: 'Family', nameTa: 'குடும்பம்', slug: 'family', description: 'Dedicated to parents, siblings and children.', descriptionTa: 'குடும்பக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600', poemsCount: 8 },
  { id: 'cat-nature', name: 'Nature', nameTa: 'இயற்கை', slug: 'nature', description: 'Praising landscapes, sky and rivers.', descriptionTa: 'இயற்கைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600', poemsCount: 9 },
  { id: 'cat-emotional', name: 'Emotional', nameTa: 'உணர்வு', slug: 'emotional', description: 'Expressing deep sentiments.', descriptionTa: 'உணர்ச்சிக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600', poemsCount: 13 },
  { id: 'cat-inspirational', name: 'Inspirational', nameTa: 'எழுச்சி', slug: 'inspirational', description: 'Spreading hope and inspiration.', descriptionTa: 'எழுச்சியூட்டும் வரிகள்.', imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600', poemsCount: 11 },
  { id: 'cat-sad', name: 'Sad', nameTa: 'சோகம்', slug: 'sad', description: 'Melancholic thoughts and poetry.', descriptionTa: 'சோகக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600', poemsCount: 15 },
  { id: 'cat-festival', name: 'Festival', nameTa: 'திருவிழா', slug: 'festival', description: 'Tributes to cultural festivities.', descriptionTa: 'பண்டிகைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=600', poemsCount: 6 },
  { id: 'cat-stories', name: 'Stories', nameTa: 'கதைகள்', slug: 'stories', description: 'Bilingual short stories and tales.', descriptionTa: 'சிறுகதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600', poemsCount: 5 }
];

export const mockPoems: Poem[] = [
  {
    "id": "poem-en-1",
    "title": "The Journey Beyond",
    "subtitle": "Death called softly, calling near...",
    "content": "Death called softly, calling near,\nBut you held on, with no fear.\nWhen your time had come to go,\nYou followed where the spirits flow.\n\nTwo paths lay—one dark, one bright,\nOne of fire, one of light.\nThe gods watched close to choose your fate\nTo see where your soul would stay.\n\nYour heart was pure, your path was clear,\nYou stepped toward peace, with nothing to fear.\nThrough heaven's gates, so wide and free,\nYou found your place, eternally.\n\nNo more pain, no more tears,\nOnly joy that lasts for years.\nA peaceful home, a place to rest,\nWhere souls are free and truly blessed.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "the-journey-beyond",
    "categorySlug": "life",
    "categoryName": "Life",
    "likesCount": 42,
    "commentsCount": 7,
    "favoritesCount": 19,
    "viewsCount": 310,
    "sharesCount": 12,
    "downloadsCount": 5,
    "readingTime": 2,
    "tags": [
      "life",
      "death",
      "peace",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-01T08:00:00.000Z",
    "updatedAt": "2026-08-01T08:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-2",
    "title": "Death",
    "subtitle": "When the time came, death reached for your hand...",
    "content": "Death called for you, ready to take you away.\n\nBut you held on, living as long as you could.\n\nWhen the time came, death reached for your hand, leading you to the unknown.\n\nTwo paths lay ahead—one of fire and suffering, the other to the gates of heaven.\n\nThe gods of death and heaven weighed your heart.\n\nWith judgment made, you took your final step—toward the light, toward peace.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "death",
    "categorySlug": "emotional",
    "categoryName": "Emotional",
    "likesCount": 35,
    "commentsCount": 5,
    "favoritesCount": 14,
    "viewsCount": 260,
    "sharesCount": 9,
    "downloadsCount": 4,
    "readingTime": 1,
    "tags": [
      "emotional",
      "death",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-01T10:00:00.000Z",
    "updatedAt": "2026-08-01T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-3",
    "title": "The Beauty of Uncertainty",
    "subtitle": "In this unpredictable world, everything is uncertain...",
    "content": "In this unpredictable world , everything is uncertain—even death .\n\nIn life , nothing can be predicted with absolute certainty .\n\nIf everything happened exactly as predicted , life would become boring .\n\nThe beauty  of life lies in its unpredictability .\n\nWhen unexpected things happen , life becomes more interesting .\n\nDay by day , we become more attached to the journey , embracing the unknown .\n\nUnpredictable moments  are like magic —unimaginable  and full of wonder .\n\nA life filled with unpredictability  and the unimaginable  is truly fulfilling .",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "the-beauty-of-uncertainty",
    "categorySlug": "inspirational",
    "categoryName": "Inspirational",
    "likesCount": 58,
    "commentsCount": 11,
    "favoritesCount": 23,
    "viewsCount": 420,
    "sharesCount": 16,
    "downloadsCount": 7,
    "readingTime": 2,
    "tags": [
      "inspirational",
      "life",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-02T09:00:00.000Z",
    "updatedAt": "2026-08-02T09:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-4",
    "title": "Life's Magic",
    "subtitle": "Life is full of twists and turns...",
    "content": "Life is full of twists and turns,\nNothing goes the way we learn.\nIf all was known, if all was clear,\nLife would be dull, year by year.\n\nSurprises come like magic bright,\nFilling days with joy and light.\nThe unknown makes each moment new,\nA journey fresh with different views.\n\nSo let life flow, embrace the way,\nEnjoy the magic every day.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "lifes-magic",
    "categorySlug": "motivation",
    "categoryName": "Motivation",
    "likesCount": 49,
    "commentsCount": 8,
    "favoritesCount": 18,
    "viewsCount": 380,
    "sharesCount": 11,
    "downloadsCount": 6,
    "readingTime": 1,
    "tags": [
      "motivation",
      "life",
      "magic",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-02T11:00:00.000Z",
    "updatedAt": "2026-08-02T11:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-5",
    "title": "The Dream World",
    "subtitle": "I jumped into bed and closed my eyes...",
    "content": "I jumped into bed and closed my eyes, slipping into a world where dreams come true.\n\nIn this place, whatever I imagine happens\n\nlove , life , and destiny  all unfold before me.\n\nThe impossible becomes possible, and the limits of reality fade away.\n\nIn dreams, I have lived many lives.\n\nI have died and been reborn, feeling every moment as if it were real.\n\nSometimes, I meet people I've never seen before, yet they feel familiar,\n\nlike lost friends from another time.\n\nThe sky changes colors , the wind whispers secrets ,\n\nand every step leads to a new adventure.\n\nI fly without wings , breathe underwater , and walk through memories long forgotten.\n\nHere, anything is possible.\n\nIn dreams,\n\nI am free.\n\nAnd when I wake, I carry a piece of that magic with me.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "the-dream-world",
    "categorySlug": "inspirational",
    "categoryName": "Inspirational",
    "likesCount": 64,
    "commentsCount": 14,
    "favoritesCount": 29,
    "viewsCount": 510,
    "sharesCount": 20,
    "downloadsCount": 9,
    "readingTime": 2,
    "tags": [
      "dreams",
      "inspirational",
      "freedom",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-03T10:00:00.000Z",
    "updatedAt": "2026-08-03T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-6",
    "title": "A Chapter Called As…",
    "subtitle": "Those days... We met like strangers...",
    "content": "Those days...\n\nWe met like strangers,\n\nCreated many memories together.\n\nMy wish is to keep those memories safe.\n\nWhenever you look at college photos,\n\nI hope you remember those days with fond memories.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "a-chapter-called-as",
    "categorySlug": "friendship",
    "categoryName": "Friendship",
    "likesCount": 52,
    "commentsCount": 9,
    "favoritesCount": 21,
    "viewsCount": 390,
    "sharesCount": 15,
    "downloadsCount": 5,
    "readingTime": 1,
    "tags": [
      "friendship",
      "memories",
      "college",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-03T14:00:00.000Z",
    "updatedAt": "2026-08-03T14:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-7",
    "title": "SOUL AWAKENING",
    "subtitle": "I want to spend a lifetime with you...",
    "content": "I want to spend a lifetime with you,\nHold your hands forever, through every breath.\nYou're the only one I want to live for,\nWithout you, my life would come to an end.\n\nSeeing you awakens my soul,\nI'm drawn to you, my heart beats whole.\nI long to hold your hands and walk with you,\nGazing into your eyes, forever true.\n\nMy heart skips a beat when I see your face,\nYour eyes speak directly to my heart's.\nI promise to love you, now and forevermore,\nIn this life and the next, I'll adore.\n\nLet's walk together, hand in hand,\nForever entwined, in love's sweet plan.\nMy eyes meet your heart, and I pledge to stay,\nWith you, my love, every step of the way.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "soul-awakening",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 87,
    "commentsCount": 18,
    "favoritesCount": 36,
    "viewsCount": 680,
    "sharesCount": 24,
    "downloadsCount": 12,
    "readingTime": 2,
    "tags": [
      "love",
      "romance",
      "forever",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-04T09:00:00.000Z",
    "updatedAt": "2026-08-04T09:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-8",
    "title": "LONGING HEART",
    "subtitle": "Your eyes mesmerize me, your voice is sweet music...",
    "content": "Your eyes mesmerize me,\nYour voice is sweet music.\nI melt like a candle,\nMy heart beats fast.\n\nWhen I think of you, time flies,\nMy heart whispers your name.\nI see your face in dreams,\nMy hands long to hold yours.\n\nYou drift away, leaving me with memories,\nBut my heart refuses to forget.\nMy love remains true,\nA one-sided affection.\n\nI search for your eyes in crowds,\nImagining us together.\nYou're the missing piece I need,\nLonging for our hearts to connect.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "longing-heart",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 73,
    "commentsCount": 15,
    "favoritesCount": 31,
    "viewsCount": 590,
    "sharesCount": 19,
    "downloadsCount": 10,
    "readingTime": 2,
    "tags": [
      "love",
      "longing",
      "unrequited",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-04T12:00:00.000Z",
    "updatedAt": "2026-08-04T12:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-9",
    "title": "Eyes That Speak…",
    "subtitle": "Eyes say more than you think...",
    "content": "Eyes say more than you think.\n\nSome eyes are so special that you can't forget them.\n\nYou might see someone's eyes and feel like you can't forget them,\n\nbut you worry that they might not notice you again.\n\nBut when you see the eyes that you love,\n\nyou can't forget them, even in a crowded room.\n\nTime stands still when your eyes meet,\n\nand your heart skips a beat.\n\nYou feel like you're stuck in that moment,\n\nand your heart is changed forever.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "eyes-that-speak",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 61,
    "commentsCount": 12,
    "favoritesCount": 27,
    "viewsCount": 470,
    "sharesCount": 14,
    "downloadsCount": 8,
    "readingTime": 1,
    "tags": [
      "love",
      "eyes",
      "romance",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-04T15:00:00.000Z",
    "updatedAt": "2026-08-04T15:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-10",
    "title": "Living Diary…",
    "subtitle": "Be a living diary to the one you love...",
    "content": "Be a living diary to the one you love.\nNot just in joy, but in silence too.\nPeople share smiles easily,\nBut hide their tears deep inside.\n\nBe there when words are hard to find.\nThey don't always need advice—just your presence.\nSometimes, being there is enough.\nIf they trust you with their pain, protect it.\n\nNever break that trust they gave you.\nIt's hard to earn back once it's lost.\nBe their safe space in this noisy world.\nBecause your quiet love can heal more than words ever could.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "living-diary",
    "categorySlug": "emotional",
    "categoryName": "Emotional",
    "likesCount": 79,
    "commentsCount": 16,
    "favoritesCount": 34,
    "viewsCount": 630,
    "sharesCount": 22,
    "downloadsCount": 11,
    "readingTime": 2,
    "tags": [
      "emotional",
      "trust",
      "love",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-05T09:00:00.000Z",
    "updatedAt": "2026-08-05T09:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-11",
    "title": "You Are Just Like a Phone…",
    "subtitle": "Life is like a phone we use every day...",
    "content": "Life is like a phone we use every day,\nBut we don't always see what's built in along the way.\nJust like the apps we never touch,\nWe forget our own strengths, though we have so much.\n\nA software update helps the phone grow,\nJust like we grow when we learn and know.\nIt makes our mind a little more clear,\nAnd helps us face things without fear.\n\nNew apps are like people we find,\nThey bring new thoughts into our mind.\nBut sometimes they hurt, and we feel low,\nAnd wonder why we let them grow.\n\nStill, every app and every change,\nTeaches us things, though it feels strange.\nAnd when we let go of what's not right,\nWe find more peace and feel more light.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "you-are-just-like-a-phone",
    "categorySlug": "life",
    "categoryName": "Life",
    "likesCount": 68,
    "commentsCount": 13,
    "favoritesCount": 28,
    "viewsCount": 540,
    "sharesCount": 17,
    "downloadsCount": 9,
    "readingTime": 2,
    "tags": [
      "life",
      "wisdom",
      "metaphor",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-05T11:00:00.000Z",
    "updatedAt": "2026-08-05T11:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-12",
    "title": "Dreams of Love…",
    "subtitle": "When I am lost inside a dream...",
    "content": "When I am lost inside a dream,\nA dream of love, so pure it seems,\nYour thoughts pull me back to stay,\nAnd wake me from my dream-filled way.\n\nReality isn't like the dream,\nIt's not as perfect, or so it seems.\nIn dreams, you do just what I want,\nBut in real life, it's not the same front.\n\nFor dreams are where I see you true,\nThe only place I can be with you.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "dreams-of-love",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 55,
    "commentsCount": 10,
    "favoritesCount": 22,
    "viewsCount": 430,
    "sharesCount": 13,
    "downloadsCount": 7,
    "readingTime": 1,
    "tags": [
      "love",
      "dreams",
      "reality",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-05T14:00:00.000Z",
    "updatedAt": "2026-08-05T14:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-en-13",
    "title": "Poetry for Me…",
    "subtitle": "When you are the poem, I search for the meaning in every line...",
    "content": "When you are the poem,\nI search for the meaning in every line,\nSome lines leave me mesmerized,\nDrawing me deeper into your mind.\n\nAs I read your words, a thought arises,\nI wish I could be the author of your poem,\nI start to believe you wrote it just for me,\nNot for others, but for my heart to see.\n\nFor when I hear the lines of your rhyme,\nMy heart melts with every word, every time.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "poetry-for-me",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 81,
    "commentsCount": 17,
    "favoritesCount": 35,
    "viewsCount": 650,
    "sharesCount": 23,
    "downloadsCount": 11,
    "readingTime": 1,
    "tags": [
      "love",
      "poetry",
      "rhyme",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-05T16:00:00.000Z",
    "updatedAt": "2026-08-05T16:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-ta-1",
    "title": "என் இதயம் உன்னிடம்",
    "subtitle": "உன் புன்னகையில் தொலைந்தேன் நான்...",
    "content": "என் இதயம் உன்னிடம் நிலைகொண்டது...\nஉன் விழி பார்வையில் என் உலகம் மலர்ந்தது.\nபேசாத வார்த்தைகளும் மெளனத்தின் மொழியாய்,\nஉன் அன்பின் ஒளியில் என் கவிதைகள் பிறந்தது.\n\nஇரவின் அமைதியில் உன் நினைவுகள் பேசுதே,\nஎன் தனிமைப் பாதையில் உன் நிழல் வருதே.\nஎன்றும் உன்னோடு வாழ வேண்டும் என் அன்பே,\nஉன் அருகாமையில் என் உயிர் வாழுதே.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "ta",
    "slug": "en-ithayam-unnidam",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 95,
    "commentsCount": 21,
    "favoritesCount": 42,
    "viewsCount": 780,
    "sharesCount": 28,
    "downloadsCount": 15,
    "readingTime": 1,
    "tags": [
      "love",
      "tamil",
      "kavithai",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-01T07:00:00.000Z",
    "updatedAt": "2026-08-01T07:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-ta-2",
    "title": "கனவுகளின் சிறகுகள்",
    "subtitle": "முயற்சிக்கு என்றும் தோல்வி இல்லை...",
    "content": "வானம் உனக்கு எல்லை இல்லை,\nமுயற்சிக்கு என்றும் தோல்வி இல்லை.\nசிறகடித்து பறப்பாய் நீயும் மேலே,\nவெற்றி உன்னைத் தேடி வரும் நாளே.\n\nவிழும் ஒவ்வொரு முறையும் எழுந்து நில்,\nஉன் பாதையில் வரும் தடைகளை வென்று செல்.\nஉன் கனவுகள் நனவாகும் காலம் வரும்,\nஉலகம் உன்னை உச்சி முகர்ந்து வாழ்த்தி நிற்கும்.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "ta",
    "slug": "kanavukalin-sirakukal",
    "categorySlug": "motivation",
    "categoryName": "Motivation",
    "likesCount": 88,
    "commentsCount": 19,
    "favoritesCount": 38,
    "viewsCount": 710,
    "sharesCount": 25,
    "downloadsCount": 13,
    "readingTime": 1,
    "tags": [
      "motivation",
      "tamil",
      "hope",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-02T08:00:00.000Z",
    "updatedAt": "2026-08-02T08:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-ta-3",
    "title": "நட்பின் அத்தியாயம்",
    "subtitle": "சொல்லாத மொழியிலும் புரியும் பாசம்...",
    "content": "கல்லூரி நாட்களின் சிரிப்புகளும்,\nபிரிந்து சென்றாலும் அழியாத நினைவுகளும்.\nசொல்லாத மொழியிலும் புரியும் பாசம்,\nஎந்த சூழ்நிலையிலும் மாறாத நேசம்.\n\nகாலங்கள் மாறினாலும் நம் நட்பு மாறாது,\nஇதயத்தின் ஆழத்தில் என்றும் மறையாது.\nஉண்மையான தோழமைக்கு ஈடு இணையே இல்லை,\nநம் நட்பின் கதைகளுக்கு என்றும் முடிவே இல்லை.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "ta",
    "slug": "natpin-athiyayam",
    "categorySlug": "friendship",
    "categoryName": "Friendship",
    "likesCount": 76,
    "commentsCount": 14,
    "favoritesCount": 30,
    "viewsCount": 620,
    "sharesCount": 21,
    "downloadsCount": 10,
    "readingTime": 1,
    "tags": [
      "friendship",
      "tamil",
      "memories",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-03T07:00:00.000Z",
    "updatedAt": "2026-08-03T07:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-ta-4",
    "title": "அன்பின் நிழல்",
    "subtitle": "மறக்க நினைத்தாலும் மனதை சுற்றும் நினைவுகள்...",
    "content": "உன் நினைவுகள் என்னை விட்டுப் பிரிவதில்லை,\nஎன் நெஞ்சம் உன்னை மறப்பதே இல்லை.\nமறக்க நினைத்தாலும் மனதை சுற்றும் நினைவுகள்,\nகாலத்தின் ஓட்டத்தில் அழியாத சுவடுகள்.\n\nஉன் அன்பின் நிழலில் கழிந்த நாட்கள்,\nஎன் வாழ்வின் மிக அழகிய தருணங்கள்.\nஎங்கு சென்றாலும் உன் குரல் கேட்குதே,\nஎன் தனிமையில் உன் முகம் தெரிகிறதே.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "ta",
    "slug": "anpin-nizal",
    "categorySlug": "emotional",
    "categoryName": "Emotional",
    "likesCount": 82,
    "commentsCount": 16,
    "favoritesCount": 35,
    "viewsCount": 660,
    "sharesCount": 23,
    "downloadsCount": 11,
    "readingTime": 1,
    "tags": [
      "emotional",
      "tamil",
      "sad",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-04T08:00:00.000Z",
    "updatedAt": "2026-08-04T08:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-ta-5",
    "title": "வாழ்க்கையின் பயணம்",
    "subtitle": "இன்பமும் துன்பமும் கலந்த பயணம்...",
    "content": "இன்பமும் துன்பமும் கலந்த பயணம்,\nஒவ்வொரு நாளும் புதிய பாடம் வழங்கும்.\nசவால்களை கண்டு அஞ்சி ஓடாமல்,\nநம்பிக்கையோடு முன்னேறி நடப்போம்.\n\nவாழ்வின் ஒவ்வொரு நொடியும் விலைமதிப்பற்றது,\nஅதை அன்போடு கடந்து செல்வது அழகானது.\nபுயலுக்கு பின் வீசும் தென்றல் போல,\nவாழ்விலும் வசந்தம் வீசும் நிச்சயம்.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "ta",
    "slug": "valkkaiyin-payanam",
    "categorySlug": "life",
    "categoryName": "Life",
    "likesCount": 71,
    "commentsCount": 12,
    "favoritesCount": 29,
    "viewsCount": 570,
    "sharesCount": 18,
    "downloadsCount": 9,
    "readingTime": 1,
    "tags": [
      "life",
      "tamil",
      "wisdom",
      "prakash"
    ],
    "status": "published",
    "createdAt": "2026-08-05T08:00:00.000Z",
    "updatedAt": "2026-08-05T08:00:00.000Z",
    "category": "poem",
    "isPublished": true
  }
];

export const mockStories: Story[] = [
  {
    "id": "story-full-1",
    "title": "Her Smile, My Memory…",
    "subtitle": "The day I first saw her, something shifted—her presence quietly settled into my thoughts...",
    "coverUrl": "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Romance",
    "content": "The day I first saw her, something shifted—her presence quietly settled into my thoughts, and ever since, she has been a part of everything I do.\n\nI’ve come to accept that life doesn’t stay the same. People evolve, feelings drift, and sometimes love exists in places we can no longer reach. I love her—not just for how she made me feel, but for who she is, even in her absence. When I’m with her, time slows down. Yet, even in the silence where our arguments once echoed, her memories bring a smile to my face.\n\nIn the quiet of the night, I find myself thinking about her smile, the way her eyes lit up when she was happy, and the comfort of her laughter. No matter how far she is, no matter how much time has passed, my heart still finds her in the quietest moments.\n\nAnd here I am, in this very moment, thinking of her… every single second, like a rhythm my soul can’t stop repeating.",
    "createdAt": "2026-08-01T14:00:00.000Z",
    "updatedAt": "2026-08-01T14:00:00.000Z",
    "readingTime": 3,
    "tags": [
      "story",
      "romance",
      "memories",
      "prakash"
    ],
    "status": "published",
    "likesCount": 112,
    "commentsCount": 24,
    "sharesCount": 35,
    "viewsCount": 890,
    "downloadsCount": 18,
    "isPublished": true
  },
  {
    "id": "story-full-2",
    "title": "With Her, Even in Silence…",
    "subtitle": "I don’t even understand why I love her more than myself...",
    "coverUrl": "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Romance",
    "content": "I don’t even understand why I love her more than myself, but all I know is I just want to be with her. And what amazes me even more is that she experiences so much with me. There are places where I haven’t even walked, but in my mind, we have explored them together.\n\nWhen she talks to me, it’s clear she feels comfortable, like she can share anything with me without hesitation. Being her safe space means more to me than any words could express. In her presence, silence isn't awkward—it's a peaceful conversation between two souls that understand each other without needing to speak.",
    "createdAt": "2026-08-02T15:00:00.000Z",
    "updatedAt": "2026-08-02T15:00:00.000Z",
    "readingTime": 2,
    "tags": [
      "story",
      "love",
      "silence",
      "prakash"
    ],
    "status": "published",
    "likesCount": 94,
    "commentsCount": 19,
    "sharesCount": 28,
    "viewsCount": 740,
    "downloadsCount": 14,
    "isPublished": true
  },
  {
    "id": "story-full-3",
    "title": "A New Beginning…",
    "subtitle": "The day I took my first step into college, I moved into a new place...",
    "coverUrl": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "College Life",
    "content": "The day I took my first step into college, I moved into a new place, and a new chapter began, filled with new experiences.\n\nI met many people—some just for a moment, and some who became special. Every day felt like a new story. Our bond grew day by day, and we shared everything with each other. The year passed, and the days slowly came to an end.\n\nOur late nights as students were ending, and we were all about to go our separate ways. It started with unknown faces, but as time passed, I got to know them, and just when everything felt right, the final page came. But those memories will stay etched in our hearts forever.",
    "createdAt": "2026-08-03T16:00:00.000Z",
    "updatedAt": "2026-08-03T16:00:00.000Z",
    "readingTime": 3,
    "tags": [
      "story",
      "college",
      "friendship",
      "prakash"
    ],
    "status": "published",
    "likesCount": 105,
    "commentsCount": 22,
    "sharesCount": 31,
    "viewsCount": 820,
    "downloadsCount": 16,
    "isPublished": true
  },
  {
    "id": "story-full-4",
    "title": "கனவுகளின் எல்லை",
    "subtitle": "சிறிய கிராமத்தில் வளர்ந்த ஒரு பெண்ணின் வெற்றிப் பயணம்.",
    "coverUrl": "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Inspirational",
    "content": "சூரியன் உதிக்கும் முன்பே நிலத்திற்குச் செல்லும் விவசாயியின் மகள் கவிதா. அவள் கைகளில் புத்தகங்களும், மனதளவில் ஆகாயத்தைத் தொடும் கனவுகளும் இருந்தன.\n\nகிராமத்து மனிதர்கள் அவளது முயற்சியைக் கண்டு சிரித்தார்கள். ஆனால் அவள் தன் நம்பிக்கையை இழக்கவில்லை. இரவுகளில் மண்ணெண்ணெய் விளக்கின் ஒளியில் படித்து, மாநிலத்தின் முதன்மைப் தேர்வில் தேர்ச்சி பெற்றாள். இன்று அவள் மாவட்ட ஆட்சியராகத் தன் சொந்தக் கிராமத்திற்குத் திரும்பியபோது, அன்று சிரித்த மனிதர்களே மலர் தூவி வரவேற்பளித்தார்கள்.",
    "createdAt": "2026-08-04T11:00:00.000Z",
    "updatedAt": "2026-08-04T11:00:00.000Z",
    "readingTime": 4,
    "tags": [
      "story",
      "tamil",
      "motivation",
      "prakash"
    ],
    "status": "published",
    "likesCount": 128,
    "commentsCount": 27,
    "sharesCount": 42,
    "viewsCount": 960,
    "downloadsCount": 22,
    "isPublished": true
  },
  {
    "id": "story-full-5",
    "title": "The Silent Guardian",
    "subtitle": "A story about quiet courage in a bustling city.",
    "coverUrl": "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Drama",
    "content": "The streetlights flickered as midnight approached in the old quarter of Chennai. Arul walked through the quiet alleys, carrying a leather satchel filled with handwritten manuscripts. For years, he had been the anonymous storyteller of the neighborhood, leaving tales of hope on doorstep benches before sunrise.\n\nTonight was different. Tonight he was leaving his final chapter—a story dedicated to the girl who read his words under the balcony light every evening. As he placed the scroll on her windowsill, a soft voice whispered from behind the wooden blinds: \"I always knew it was you.\" Arul smiled in the shadows, knowing that some stories never end.",
    "createdAt": "2026-08-05T10:00:00.000Z",
    "updatedAt": "2026-08-05T10:00:00.000Z",
    "readingTime": 3,
    "tags": [
      "story",
      "romance",
      "chennai",
      "prakash"
    ],
    "status": "published",
    "likesCount": 89,
    "commentsCount": 16,
    "sharesCount": 24,
    "viewsCount": 670,
    "downloadsCount": 13,
    "isPublished": true
  }
];

export const mockQuotes: Quote[] = [
  {
    "id": "qte-prakash-1",
    "content": "Life is not easy...The hardest feeling is when you really want to talk to someone you love, but you can't.Sometimes, silence hurts more than words. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 15,
    "commentsCount": 2,
    "viewsCount": 110,
    "sharesCount": 4,
    "createdAt": "2026-08-02T00:24:59.964Z"
  },
  {
    "id": "qte-prakash-2",
    "content": "Something I wanted so badly before...is now just a memory.That memory still makes me smile.I have the strength to move on...but my heart doesn't. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 17,
    "commentsCount": 3,
    "viewsCount": 125,
    "sharesCount": 5,
    "createdAt": "2026-08-02T01:24:59.964Z"
  },
  {
    "id": "qte-prakash-3",
    "content": "When someone becomes very close to you...the biggest fear is losing them. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 19,
    "commentsCount": 4,
    "viewsCount": 140,
    "sharesCount": 6,
    "createdAt": "2026-08-02T02:24:59.966Z"
  },
  {
    "id": "qte-prakash-4",
    "content": "No one is too busy.If someone truly cares about you,they will always make time for you. ✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 21,
    "commentsCount": 2,
    "viewsCount": 155,
    "sharesCount": 7,
    "createdAt": "2026-08-02T03:24:59.966Z"
  },
  {
    "id": "qte-prakash-5",
    "content": "We don't know someone's value when they are with us.We understand it only after they leave. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Life",
    "tags": [
      "life",
      "prakash"
    ],
    "status": "published",
    "likesCount": 23,
    "commentsCount": 3,
    "viewsCount": 170,
    "sharesCount": 4,
    "createdAt": "2026-08-02T04:24:59.966Z"
  },
  {
    "id": "qte-prakash-6",
    "content": "Everything should have a limit.If we go beyond that limit,the same thing can become the reason for our biggest pain. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 25,
    "commentsCount": 4,
    "viewsCount": 185,
    "sharesCount": 5,
    "createdAt": "2026-08-02T05:24:59.966Z"
  },
  {
    "id": "qte-prakash-7",
    "content": "You can return something you don't like after buying it.But some decisions in life cannot be changed.So think before you decide. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 27,
    "commentsCount": 2,
    "viewsCount": 200,
    "sharesCount": 6,
    "createdAt": "2026-08-02T06:24:59.966Z"
  },
  {
    "id": "qte-prakash-8",
    "content": "Sometimes...after taking all the blame,we just want to disappear quietly from everyone's life. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 29,
    "commentsCount": 3,
    "viewsCount": 215,
    "sharesCount": 7,
    "createdAt": "2026-08-02T07:24:59.966Z"
  },
  {
    "id": "qte-prakash-9",
    "content": "Just because you love someone...doesn't mean they will love you back.Sometimes, love is one-sided. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 31,
    "commentsCount": 4,
    "viewsCount": 230,
    "sharesCount": 4,
    "createdAt": "2026-08-02T08:24:59.966Z"
  },
  {
    "id": "qte-prakash-10",
    "content": "Life doesn't always go the way we want.Sometimes we have to accept what happensand keep moving forward. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 33,
    "commentsCount": 2,
    "viewsCount": 245,
    "sharesCount": 5,
    "createdAt": "2026-08-02T09:24:59.967Z"
  },
  {
    "id": "qte-prakash-11",
    "content": "The things I love the most...always seem to go far away from me.It feels like nothing stays with me forever. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 35,
    "commentsCount": 3,
    "viewsCount": 260,
    "sharesCount": 6,
    "createdAt": "2026-08-02T10:24:59.967Z"
  },
  {
    "id": "qte-prakash-12",
    "content": "When someone you love leaves...it's not easy to forget them.They were a big part of your heart. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 37,
    "commentsCount": 4,
    "viewsCount": 275,
    "sharesCount": 7,
    "createdAt": "2026-08-02T11:24:59.967Z"
  },
  {
    "id": "qte-prakash-13",
    "content": "Leaving may be easy for us...but for someone who truly loves us,it can be very painful. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 39,
    "commentsCount": 2,
    "viewsCount": 290,
    "sharesCount": 4,
    "createdAt": "2026-08-02T12:24:59.967Z"
  },
  {
    "id": "qte-prakash-14",
    "content": "There comes a time...when nothing hurts anymore.Not because you're strong,but because your heart is already tired. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 41,
    "commentsCount": 3,
    "viewsCount": 305,
    "sharesCount": 5,
    "createdAt": "2026-08-02T13:24:59.967Z"
  },
  {
    "id": "qte-prakash-15",
    "content": "When the person you love is far away,you're scared something might happen to them.When they're with you,you're scared of losing them.That's what true love feels like. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 43,
    "commentsCount": 4,
    "viewsCount": 320,
    "sharesCount": 6,
    "createdAt": "2026-08-02T14:24:59.967Z"
  },
  {
    "id": "qte-prakash-16",
    "content": "If we're gone one day...people may miss us for some time.But slowly, life goes on.Everyone gets replaced one day. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 45,
    "commentsCount": 2,
    "viewsCount": 335,
    "sharesCount": 7,
    "createdAt": "2026-08-02T15:24:59.967Z"
  },
  {
    "id": "qte-prakash-17",
    "content": "When I stopped expecting too much from life...my heart felt a little lighter.I'm not fully happy,but I'm more peaceful now. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 47,
    "commentsCount": 3,
    "viewsCount": 350,
    "sharesCount": 4,
    "createdAt": "2026-08-02T16:24:59.967Z"
  },
  {
    "id": "qte-prakash-18",
    "content": "If you find someone better than me...don't stay with me because you feel bad.You deserve the best in life. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 49,
    "commentsCount": 4,
    "viewsCount": 365,
    "sharesCount": 5,
    "createdAt": "2026-08-02T17:24:59.967Z"
  },
  {
    "id": "qte-prakash-19",
    "content": "I want you to be the best photo in my camera. 📸🖤And I want to be the onewho captures that moment forever.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 51,
    "commentsCount": 2,
    "viewsCount": 380,
    "sharesCount": 6,
    "createdAt": "2026-08-02T18:24:59.967Z"
  },
  {
    "id": "qte-prakash-20",
    "content": "Don't think too much about everything.Life is already moving forward.Stay calm...and go with the flow. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 53,
    "commentsCount": 3,
    "viewsCount": 395,
    "sharesCount": 7,
    "createdAt": "2026-08-02T19:24:59.967Z"
  },
  {
    "id": "qte-prakash-21",
    "content": "Something that means nothing to us...may be someone else's biggest dream.Life is all about how we see things. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 55,
    "commentsCount": 4,
    "viewsCount": 410,
    "sharesCount": 4,
    "createdAt": "2026-08-02T20:24:59.967Z"
  },
  {
    "id": "qte-prakash-22",
    "content": "The hardest feeling is...thinking that your absence doesn't matter to anyone.Sometimes, I even wonder...would anyone notice if I was gone? 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 57,
    "commentsCount": 2,
    "viewsCount": 425,
    "sharesCount": 5,
    "createdAt": "2026-08-02T21:24:59.967Z"
  },
  {
    "id": "qte-prakash-23",
    "content": "If you truly love someone...distance, pain, or silence can't change your feelings.Your heart will always look for them. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 59,
    "commentsCount": 3,
    "viewsCount": 440,
    "sharesCount": 6,
    "createdAt": "2026-08-02T22:24:59.967Z"
  },
  {
    "id": "qte-prakash-24",
    "content": "You can be surrounded by many people...and still feel lonely inside.Sometimes, that pain is worse than being alone. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 61,
    "commentsCount": 4,
    "viewsCount": 455,
    "sharesCount": 7,
    "createdAt": "2026-08-02T23:24:59.967Z"
  },
  {
    "id": "qte-prakash-25",
    "content": "In a world where everything is replaced...a person who tries to fix things instead of giving upis very rare. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 63,
    "commentsCount": 2,
    "viewsCount": 470,
    "sharesCount": 4,
    "createdAt": "2026-08-03T00:24:59.967Z"
  },
  {
    "id": "qte-prakash-26",
    "content": "We only know our side of the story.The other person may also be hiding a lot of pain.That's why many misunderstandings happen. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 65,
    "commentsCount": 3,
    "viewsCount": 485,
    "sharesCount": 5,
    "createdAt": "2026-08-03T01:24:59.967Z"
  },
  {
    "id": "qte-prakash-27",
    "content": "True friendship doesn't need daily conversations.Even if we don't talk every day,the bond stays the same. 🫂💗",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 67,
    "commentsCount": 4,
    "viewsCount": 500,
    "sharesCount": 6,
    "createdAt": "2026-08-03T02:24:59.967Z"
  },
  {
    "id": "qte-prakash-28",
    "content": "Sometimes...someone is quietly wishingto have just one conversation with you. 🌙One day, that wish may come true. ✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 69,
    "commentsCount": 2,
    "viewsCount": 515,
    "sharesCount": 7,
    "createdAt": "2026-08-03T03:24:59.967Z"
  },
  {
    "id": "qte-prakash-29",
    "content": "Maybe it took time...maybe it took distance...But life finally brought you together.And talking to them felt like everything was right again. 😊✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 71,
    "commentsCount": 3,
    "viewsCount": 530,
    "sharesCount": 4,
    "createdAt": "2026-08-03T04:24:59.967Z"
  },
  {
    "id": "qte-prakash-30",
    "content": "Some things should be repaired, not replaced.Because memories, love, and emotionscan never be replaced by something new.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 73,
    "commentsCount": 4,
    "viewsCount": 545,
    "sharesCount": 5,
    "createdAt": "2026-08-03T05:24:59.967Z"
  },
  {
    "id": "qte-prakash-31",
    "content": "When you talk to your favorite person every day...even one day without talking to themfeels incomplete. 🖤🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 75,
    "commentsCount": 2,
    "viewsCount": 560,
    "sharesCount": 6,
    "createdAt": "2026-08-03T06:24:59.967Z"
  },
  {
    "id": "qte-prakash-32",
    "content": "How lucky would I be...if someone could understand my paineven when I say, \"I'm fine.\" 💗",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 77,
    "commentsCount": 3,
    "viewsCount": 575,
    "sharesCount": 7,
    "createdAt": "2026-08-03T07:24:59.967Z"
  },
  {
    "id": "qte-prakash-33",
    "content": "No matter how bad my day is...I still wait happily for one person's message.Some people bring peace to our hearts. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Life",
    "tags": [
      "life",
      "prakash"
    ],
    "status": "published",
    "likesCount": 79,
    "commentsCount": 4,
    "viewsCount": 590,
    "sharesCount": 4,
    "createdAt": "2026-08-03T08:24:59.967Z"
  },
  {
    "id": "qte-prakash-34",
    "content": "All I want is...to see the people I love smile.Their happiness makes me happy too. 🌙🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 81,
    "commentsCount": 2,
    "viewsCount": 605,
    "sharesCount": 5,
    "createdAt": "2026-08-03T09:24:59.967Z"
  },
  {
    "id": "qte-prakash-35",
    "content": "Life is not easy...when you think too muchand feel everything deeply. 🖤🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 83,
    "commentsCount": 3,
    "viewsCount": 620,
    "sharesCount": 6,
    "createdAt": "2026-08-03T10:24:59.967Z"
  },
  {
    "id": "qte-prakash-36",
    "content": "My heart wants to say so much...but I don't have anyone to listen.Sometimes, silence hurts the most. 🖤🥀",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 85,
    "commentsCount": 4,
    "viewsCount": 635,
    "sharesCount": 7,
    "createdAt": "2026-08-03T11:24:59.967Z"
  },
  {
    "id": "qte-prakash-37",
    "content": "I know what I'm hoping for may never happen...but my heart still hopes every single day. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 87,
    "commentsCount": 2,
    "viewsCount": 650,
    "sharesCount": 4,
    "createdAt": "2026-08-03T12:24:59.967Z"
  },
  {
    "id": "qte-prakash-38",
    "content": "Dogs may live for only a few years...but they spend their whole lifeloving us without any conditions. 🐾🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 89,
    "commentsCount": 3,
    "viewsCount": 665,
    "sharesCount": 5,
    "createdAt": "2026-08-03T13:24:59.967Z"
  },
  {
    "id": "qte-prakash-39",
    "content": "Not everything you lose is really a loss.If it's meant for you,it will come back.If it's not,no one can make it stay forever. 🖤🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 91,
    "commentsCount": 4,
    "viewsCount": 680,
    "sharesCount": 6,
    "createdAt": "2026-08-03T14:24:59.967Z"
  },
  {
    "id": "qte-prakash-40",
    "content": "I don't even remember...the last time I slept peacefully.These days, my thoughts stay awake all night. 🌙🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 93,
    "commentsCount": 2,
    "viewsCount": 695,
    "sharesCount": 7,
    "createdAt": "2026-08-03T15:24:59.967Z"
  },
  {
    "id": "qte-prakash-41",
    "content": "I miss those nights...when my mind was calmand my heart felt light. 🖤🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 95,
    "commentsCount": 3,
    "viewsCount": 710,
    "sharesCount": 4,
    "createdAt": "2026-08-03T16:24:59.967Z"
  },
  {
    "id": "qte-prakash-42",
    "content": "Real comfort is not someone saying...\"Stop crying.\"It's someone saying,\"Please don't cry... It hurts me to see you like this.\" 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 97,
    "commentsCount": 4,
    "viewsCount": 725,
    "sharesCount": 5,
    "createdAt": "2026-08-03T17:24:59.967Z"
  },
  {
    "id": "qte-prakash-43",
    "content": "Some people are online...but they don't reply to your message.If they really wanted to talk to you,even one minute would be enough. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 99,
    "commentsCount": 2,
    "viewsCount": 740,
    "sharesCount": 6,
    "createdAt": "2026-08-03T18:24:59.967Z"
  },
  {
    "id": "qte-prakash-44",
    "content": "Sometimes I wish I was a jellyfish... 🌊🖤No heart.No emotions.No pain.Just living peacefully,without getting hurt by anyone.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 101,
    "commentsCount": 3,
    "viewsCount": 755,
    "sharesCount": 7,
    "createdAt": "2026-08-03T19:24:59.967Z"
  },
  {
    "id": "qte-prakash-45",
    "content": "I stood far away...but my eyes were looking only for you. ✨I kept watching you until you were out of sight.I stayed away because I was afraid of getting lost in your eyes. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 103,
    "commentsCount": 4,
    "viewsCount": 770,
    "sharesCount": 4,
    "createdAt": "2026-08-03T20:24:59.967Z"
  },
  {
    "id": "qte-prakash-46",
    "content": "I started walking away from everything...I don't know where I'm going.But every step reminds meof the pain I've been through. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 105,
    "commentsCount": 2,
    "viewsCount": 785,
    "sharesCount": 5,
    "createdAt": "2026-08-03T21:24:59.967Z"
  },
  {
    "id": "qte-prakash-47",
    "content": "You are beyond time...Even if time changes,my love for you never will.You started as a poem...but became the story of my life. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 107,
    "commentsCount": 3,
    "viewsCount": 800,
    "sharesCount": 6,
    "createdAt": "2026-08-03T22:24:59.967Z"
  },
  {
    "id": "qte-prakash-48",
    "content": "Sometimes...we make a decision without thinking.Later, we realizehow much it hurt the other person. 🖤The saddest part is...we understand their painonly after they tell us. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 109,
    "commentsCount": 4,
    "viewsCount": 815,
    "sharesCount": 7,
    "createdAt": "2026-08-03T23:24:59.967Z"
  },
  {
    "id": "qte-prakash-49",
    "content": "Sometimes we hurt the people closest to us the most...because we never think they'll leave.But one day,they slowly change because of the pain we caused. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 111,
    "commentsCount": 2,
    "viewsCount": 830,
    "sharesCount": 4,
    "createdAt": "2026-08-04T00:24:59.967Z"
  },
  {
    "id": "qte-prakash-50",
    "content": "I always end up hurting the people who care about me the most...Even when I don't mean to,my actions hurt them. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 113,
    "commentsCount": 3,
    "viewsCount": 845,
    "sharesCount": 5,
    "createdAt": "2026-08-04T01:24:59.967Z"
  },
  {
    "id": "qte-prakash-51",
    "content": "Sometimes I feel...I gave them less lovethan the pain I gave them.Especially the peoplewho cared about me the most. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 115,
    "commentsCount": 4,
    "viewsCount": 860,
    "sharesCount": 6,
    "createdAt": "2026-08-04T02:24:59.967Z"
  },
  {
    "id": "qte-prakash-52",
    "content": "My face smiled...but my heart cried.I didn't tell anyone.No one knew.I kept all the pain inside. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 117,
    "commentsCount": 2,
    "viewsCount": 875,
    "sharesCount": 7,
    "createdAt": "2026-08-04T03:24:59.967Z"
  },
  {
    "id": "qte-prakash-53",
    "content": "There was no shoulder to cry on...no one to lean on. 🖤The people I needed were there...but they were too far away.Only their memories stayed with me.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 119,
    "commentsCount": 3,
    "viewsCount": 890,
    "sharesCount": 4,
    "createdAt": "2026-08-04T04:24:59.967Z"
  },
  {
    "id": "qte-prakash-54",
    "content": "I'm trying to forget the person who forgot me... 🖤But every day,I end up talking to their memories instead.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 121,
    "commentsCount": 4,
    "viewsCount": 905,
    "sharesCount": 5,
    "createdAt": "2026-08-04T05:24:59.967Z"
  },
  {
    "id": "qte-prakash-55",
    "content": "Every time I tried to forget you...I came back with more memories of you. 🖤Even my heartdidn't want to let you go.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 123,
    "commentsCount": 2,
    "viewsCount": 920,
    "sharesCount": 6,
    "createdAt": "2026-08-04T06:24:59.967Z"
  },
  {
    "id": "qte-prakash-56",
    "content": "Life brought you into my life...and after meeting you,life felt beautiful again. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 125,
    "commentsCount": 3,
    "viewsCount": 935,
    "sharesCount": 7,
    "createdAt": "2026-08-04T07:24:59.967Z"
  },
  {
    "id": "qte-prakash-57",
    "content": "When we stayed silent...our eyes spoke everything. 🖤In one moment,our eyes shared thousands of feelings.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 127,
    "commentsCount": 4,
    "viewsCount": 950,
    "sharesCount": 4,
    "createdAt": "2026-08-04T08:24:59.967Z"
  },
  {
    "id": "qte-prakash-58",
    "content": "You know I like you.You know I love you.But only I knowhow deeply I love you. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 129,
    "commentsCount": 2,
    "viewsCount": 965,
    "sharesCount": 5,
    "createdAt": "2026-08-04T09:24:59.967Z"
  },
  {
    "id": "qte-prakash-59",
    "content": "When you're close...I can only look at you.When you're far away...I can only talk to you.I can't talk when you're near.I can't see you when you're far.Why does this relationship hurt so much? 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 131,
    "commentsCount": 3,
    "viewsCount": 980,
    "sharesCount": 6,
    "createdAt": "2026-08-04T10:24:59.967Z"
  },
  {
    "id": "qte-prakash-60",
    "content": "He loved her...more than he loved himself. 🖤A heart that never cared about itselfstarted caring only for her.Every day,he missed her more and more.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 133,
    "commentsCount": 4,
    "viewsCount": 995,
    "sharesCount": 7,
    "createdAt": "2026-08-04T11:24:59.967Z"
  },
  {
    "id": "qte-prakash-61",
    "content": "I met her again...with the same feeling I had the first time. 🖤Time has changed...but my heart hasn't.Every time I see her,I fall in love with her all over again.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 135,
    "commentsCount": 2,
    "viewsCount": 1010,
    "sharesCount": 4,
    "createdAt": "2026-08-04T12:24:59.967Z"
  },
  {
    "id": "qte-prakash-62",
    "content": "I don't have the right to ask you to stay...and I don't have the courage to ask you to leave. 🖤But my heart stays with you every day.Wherever life takes me,I'll always carry your memories with me.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 137,
    "commentsCount": 3,
    "viewsCount": 1025,
    "sharesCount": 5,
    "createdAt": "2026-08-04T13:24:59.967Z"
  },
  {
    "id": "qte-prakash-63",
    "content": "I called it love... ❤️✨But you became my whole world.\nYou are a beautiful storythat was never written anywhere.\nThere is not a single nightwhen I don't think about you.\nThere is not a single momentwhen you don't come to my mind.\nYou are the poemI never told anyone about.\nI thought you were just a poem...but you became the greatest story of my life.\nI called it love...and you became my entire world. ❤️✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 139,
    "commentsCount": 4,
    "viewsCount": 1040,
    "sharesCount": 6,
    "createdAt": "2026-08-04T14:24:59.969Z"
  }
];

export const mockComments: Comment[] = [];
export const mockCollections: Collection[] = [];
export const mockAudioTracks: AudioTrack[] = [];
export const mockAchievements: Achievement[] = [];
export const mockActivityLogs: ActivityLog[] = [];
export const mockTags: string[] = ['love', 'breakup', 'motivation', 'friendship', 'life', 'family', 'nature', 'emotional', 'inspirational', 'sad', 'festival', 'stories'];
