import { User, Poem, Category, Comment, Collection, AudioTrack, Achievement, ActivityLog, Story, Quote } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-id',
    name: 'Administrator',
    email: 'admin@siragii.com',
    username: 'admin',
    role: 'admin',
    followersCount: 15,
    followingCount: 3,
    createdAt: '2026-01-15T00:00:00Z',
  }
];

export const mockCategories: Category[] = [
  { id: 'cat-love', name: 'Love', nameTa: 'காதல்', slug: 'love', description: 'Love and romance poetry.', descriptionTa: 'காதல் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600', poemsCount: 14 },
  { id: 'cat-breakup', name: 'Breakup', nameTa: 'பிரிவு', slug: 'breakup', description: 'Breakup and separation poems.', descriptionTa: 'பிரிவு கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600', poemsCount: 8 },
  { id: 'cat-motivation', name: 'Motivation', nameTa: 'ஊக்கம்', slug: 'motivation', description: 'Motivational and inspirational stanzas.', descriptionTa: 'ஊக்கமூட்டும் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600', poemsCount: 12 },
  { id: 'cat-friendship', name: 'Friendship', nameTa: 'நட்பு', slug: 'friendship', description: 'Celebrating bonds and friendships.', descriptionTa: 'நட்புக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600', poemsCount: 10 },
  { id: 'cat-life', name: 'Life', nameTa: 'வாழ்க்கை', slug: 'life', description: 'Reflections on the journey of life.', descriptionTa: 'வாழ்க்கைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600', poemsCount: 15 },
  { id: 'cat-family', name: 'Family', nameTa: 'குடும்பம்', slug: 'family', description: 'Dedicated to parents, siblings and children.', descriptionTa: 'குடும்பக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600', poemsCount: 6 },
  { id: 'cat-nature', name: 'Nature', nameTa: 'இயற்கை', slug: 'nature', description: 'Praising landscapes, sky and rivers.', descriptionTa: 'இயற்கைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600', poemsCount: 7 },
  { id: 'cat-emotional', name: 'Emotional', nameTa: 'உணர்வு', slug: 'emotional', description: 'Expressing deep sentiments.', descriptionTa: 'உணர்ச்சிக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600', poemsCount: 11 },
  { id: 'cat-inspirational', name: 'Inspirational', nameTa: 'எழுச்சி', slug: 'inspirational', description: 'Spreading hope and inspiration.', descriptionTa: 'எழுச்சியூட்டும் வரிகள்.', imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600', poemsCount: 9 },
  { id: 'cat-sad', name: 'Sad', nameTa: 'சோகம்', slug: 'sad', description: 'Melancholic thoughts and poetry.', descriptionTa: 'சோகக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600', poemsCount: 13 },
  { id: 'cat-festival', name: 'Festival', nameTa: 'திருவிழா', slug: 'festival', description: 'Tributes to cultural festivities.', descriptionTa: 'பண்டிகைக் கவிதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=600', poemsCount: 5 },
  { id: 'cat-stories', name: 'Stories', nameTa: 'கதைகள்', slug: 'stories', description: 'Bilingual short stories and tales.', descriptionTa: 'சிறுகதைகள்.', imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600', poemsCount: 3 }
];

export const mockPoems: Poem[] = [
  {
    "id": "poem-seed-1",
    "title": "Death called softly, calling near,",
    "subtitle": "A beautiful verse about love",
    "content": "But you held on, with no fear.\nWhen your time had come to go,\nYou followed where the spirits flow.\n\nTwo paths lay—one dark, one bright,\nOne of fire, one of light.\n\"The gods watched close to choose your fate\nTo see where your soul would stay.\n\nYour heart was pure, your path was clear,\nYou stepped toward peace, with nothing to fear.\nThrough heaven’s gates, so wide and free,\nYou found your place, eternally.\n\nNo more pain, no more tears,\nOnly joy that lasts for years.\nA peaceful home, a place to rest,\nWhere souls are free and truly blessed.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "death-called-softly-calling-near",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 12,
    "commentsCount": 3,
    "favoritesCount": 8,
    "viewsCount": 140,
    "sharesCount": 5,
    "downloadsCount": 2,
    "readingTime": 1,
    "tags": [
      "love",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-01T10:00:00.000Z",
    "updatedAt": "2026-08-01T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-2",
    "title": "Death called for you, ready to take you away.",
    "subtitle": "A beautiful verse about life",
    "content": "But you held on, living as long as you could.\n\nWhen the time came, death reached for your hand, leading you to the unknown.\n\nTwo paths lay ahead—one of fire and suffering, the other to the gates of heaven.\n\nThe gods of death and heaven weighed your heart.\n\nWith judgment made, you took your final step—toward the light, toward peace.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "death-called-for-you-ready-to-take-you-a",
    "categorySlug": "life",
    "categoryName": "Life",
    "likesCount": 17,
    "commentsCount": 5,
    "favoritesCount": 11,
    "viewsCount": 185,
    "sharesCount": 6,
    "downloadsCount": 3,
    "readingTime": 1,
    "tags": [
      "life",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-02T10:00:00.000Z",
    "updatedAt": "2026-08-02T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-3",
    "title": "The Beauty of Uncertainty",
    "subtitle": "A beautiful verse about motivation",
    "content": "In this unpredictable world , everything is uncertain—even death .\n\nIn life , nothing can be predicted with absolute certainty .\n\nIf everything happened exactly as predicted , life would become boring .\n\nThe beauty  of life lies in its unpredictability .\n\nWhen unexpected things happen , life becomes more interesting .\n\nDay by day , we become more attached to the journey , embracing the unknown .\n\nUnpredictable moments  are like magic —unimaginable  and full of wonder .\n\nA life filled with unpredictability  and the unimaginable  is truly fulfilling .",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "the-beauty-of-uncertainty",
    "categorySlug": "motivation",
    "categoryName": "Motivation",
    "likesCount": 22,
    "commentsCount": 7,
    "favoritesCount": 14,
    "viewsCount": 230,
    "sharesCount": 7,
    "downloadsCount": 4,
    "readingTime": 1,
    "tags": [
      "motivation",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-03T10:00:00.000Z",
    "updatedAt": "2026-08-03T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-4",
    "title": "Life’s Magic",
    "subtitle": "A beautiful verse about emotional",
    "content": "Life is full of twists and turns,\n\nNothing goes the way we learn.\n\nIf all was known, if all was clear,\n\nLife would be dull, year by year.\n\nSurprises come like magic bright,\n\nFilling days with joy and light.\n\nThe unknown makes each moment new,\n\nA journey fresh with different views.\n\nSo let life flow, embrace the way,\n\nEnjoy the magic every day.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "lifes-magic",
    "categorySlug": "emotional",
    "categoryName": "Emotional",
    "likesCount": 27,
    "commentsCount": 9,
    "favoritesCount": 17,
    "viewsCount": 275,
    "sharesCount": 8,
    "downloadsCount": 5,
    "readingTime": 1,
    "tags": [
      "emotional",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-04T10:00:00.000Z",
    "updatedAt": "2026-08-04T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-5",
    "title": "The Dream World",
    "subtitle": "A beautiful verse about inspirational",
    "content": "I jumped into bed and closed my eyes, slipping into a world where dreams come true.\n\nIn this place, whatever I imagine happens\n\nlove , life , and destiny  all unfold before me.\n\nThe impossible becomes possible, and the limits of reality fade away.\n\nIn dreams, I have lived many lives.\n\nI have died and been reborn, feeling every moment as if it were real.\n\nSometimes, I meet people I’ve never seen before, yet they feel familiar,\n\nlike lost friends from another time.\n\nThe sky changes colors , the wind whispers secrets ,\n\nand every step leads to a new adventure.\n\nI fly without wings , breathe underwater , and walk through memories long forgotten.\n\nHere, anything is possible.\n\nIn dreams,\n\nI am free.\n\nAnd when I wake, I carry a piece of that magic with me.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "the-dream-world",
    "categorySlug": "inspirational",
    "categoryName": "Inspirational",
    "likesCount": 32,
    "commentsCount": 11,
    "favoritesCount": 20,
    "viewsCount": 320,
    "sharesCount": 9,
    "downloadsCount": 6,
    "readingTime": 2,
    "tags": [
      "inspirational",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-05T10:00:00.000Z",
    "updatedAt": "2026-08-05T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-6",
    "title": "A Chapter Called As….",
    "subtitle": "A beautiful verse about sad",
    "content": "Those days...\n\nWe met like strangers,\n\nCreated many memories together.\n\nMy wish is to keep those memories safe.\n\nWhenever you look at college photos,\n\nI hope you remember those days with fond memories.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "a-chapter-called-as…",
    "categorySlug": "sad",
    "categoryName": "Sad",
    "likesCount": 37,
    "commentsCount": 13,
    "favoritesCount": 23,
    "viewsCount": 365,
    "sharesCount": 10,
    "downloadsCount": 7,
    "readingTime": 1,
    "tags": [
      "sad",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-06T10:00:00.000Z",
    "updatedAt": "2026-08-06T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-7",
    "title": "SOUL  AWAKENING",
    "subtitle": "A beautiful verse about friendship",
    "content": "I want to spend a lifetime with you,\nHold your hands forever, through every breath.\nYou're the only one I want to live for,\nWithout you, my life would come to an end.\n\nSeeing you awakens my soul,\nI'm drawn to you, my heart beats whole.\nI long to hold your hands and walk with you,\nGazing into your eyes, forever true.\n\nMy heart skips a beat when I see your face,\nYour eyes speak directly to my heart's.\nI promise to love you, now and forevermore,\nIn this life and the next, I'll adore.\n\nLet's walk together, hand in hand,\nForever entwined, in love's sweet plan.\nMy eyes meet your heart, and I pledge to stay,\nWith you, my love, every step of the way.\"\n\n\n\nLONGING  HEART",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "soul--awakening",
    "categorySlug": "friendship",
    "categoryName": "Friendship",
    "likesCount": 42,
    "commentsCount": 15,
    "favoritesCount": 26,
    "viewsCount": 410,
    "sharesCount": 11,
    "downloadsCount": 8,
    "readingTime": 2,
    "tags": [
      "friendship",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-07T10:00:00.000Z",
    "updatedAt": "2026-08-07T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-8",
    "title": "Your eyes mesmerize me,",
    "subtitle": "A beautiful verse about love",
    "content": "Your voice is sweet music.\nI melt like a candle,\nMy heart beats fast.\n\nWhen I think of you, time flies,\nMy heart whispers your name.\nI see your face in dreams,\nMy hands long to hold yours.\n\nYou drift away, leaving me with memories,\nBut my heart refuses to forget.\nMy love remains true,\nA one-sided affection.\n\nI search for your eyes in crowds,\nImagining us together.\nYou're the missing piece I need,\nLonging for our hearts to connect.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "your-eyes-mesmerize-me",
    "categorySlug": "love",
    "categoryName": "Love",
    "likesCount": 47,
    "commentsCount": 17,
    "favoritesCount": 29,
    "viewsCount": 455,
    "sharesCount": 12,
    "downloadsCount": 9,
    "readingTime": 1,
    "tags": [
      "love",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-08T10:00:00.000Z",
    "updatedAt": "2026-08-08T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-9",
    "title": "Eyes say more than you think.",
    "subtitle": "A beautiful verse about life",
    "content": "Some eyes are so special that you can't forget them.\n\nYou might see someone's eyes and feel like you can't forget them,\n\nbut you worry that they might not notice you again.\n\nBut when you see the eyes that you love,\n\nyou can't forget them, even in a crowded room.\n\nTime stands still when your eyes meet,\n\nand your heart skips a beat.\n\nYou feel like you're stuck in that moment,\n\nand your heart is changed forever.\"",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "eyes-say-more-than-you-think",
    "categorySlug": "life",
    "categoryName": "Life",
    "likesCount": 52,
    "commentsCount": 19,
    "favoritesCount": 32,
    "viewsCount": 500,
    "sharesCount": 13,
    "downloadsCount": 10,
    "readingTime": 1,
    "tags": [
      "life",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-10",
    "title": "Be a living diary to the one you love.",
    "subtitle": "A beautiful verse about motivation",
    "content": "Not just in joy, but in silence too.\nPeople share smiles easily,\nBut hide their tears deep inside.\n\nBe there when words are hard to find.\nThey don’t always need advice—just your presence.\nSometimes, being there is enough.\nIf they trust you with their pain, protect it.\n\nNever break that trust they gave you.\nIt’s hard to earn back once it's lost.\nBe their safe space in this noisy world.\nBecause your quiet love can heal more than words ever could.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "be-a-living-diary-to-the-one-you-love",
    "categorySlug": "motivation",
    "categoryName": "Motivation",
    "likesCount": 57,
    "commentsCount": 21,
    "favoritesCount": 35,
    "viewsCount": 545,
    "sharesCount": 14,
    "downloadsCount": 11,
    "readingTime": 1,
    "tags": [
      "motivation",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-11",
    "title": "A New Beginning…",
    "subtitle": "A beautiful verse about emotional",
    "content": "The day I took my first step into college,\nI moved into a new place,\nA new chapter began,\nFilled with new experiences.\n\nI met many people—\nSome just for a moment,\nAnd some who became special.\nEvery day felt like a new story.\n\nOur bond grew day by day,\nWe shared everything with each other.\nThe year passed,\nAnd the days slowly came to an end.\n\nOur late nights as students were ending,\nWe were all about to go our separate ways.\n\nIt started with unknown faces,\nBut as time passed,\nI got to know them,\nAnd just when everything felt right...\nThe final page came..",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "a-new-beginning…",
    "categorySlug": "emotional",
    "categoryName": "Emotional",
    "likesCount": 62,
    "commentsCount": 23,
    "favoritesCount": 38,
    "viewsCount": 590,
    "sharesCount": 15,
    "downloadsCount": 12,
    "readingTime": 1,
    "tags": [
      "emotional",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-12",
    "title": "Life is like a phone we use every day,",
    "subtitle": "A beautiful verse about inspirational",
    "content": "But we don’t always see what’s built in along the way.\nJust like the apps we never touch,\nWe forget our own strengths, though we have so much.\n\nA software update helps the phone grow,\nJust like we grow when we learn and know.\nIt makes our mind a little more clear,\nAnd helps us face things without fear.\n\nNew apps are like people we find,\nThey bring new thoughts into our mind.\nBut sometimes they hurt, and we feel low,\nAnd wonder why we let them grow.\n\nStill, every app and every change,\nTeaches us things, though it feels strange.\nAnd when we let go of what’s not right,\nWe find more peace and feel more light\n\nDreams of Love…",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "life-is-like-a-phone-we-use-every-day",
    "categorySlug": "inspirational",
    "categoryName": "Inspirational",
    "likesCount": 67,
    "commentsCount": 25,
    "favoritesCount": 41,
    "viewsCount": 635,
    "sharesCount": 16,
    "downloadsCount": 13,
    "readingTime": 2,
    "tags": [
      "inspirational",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-13",
    "title": "When I am lost inside a dream,",
    "subtitle": "A beautiful verse about sad",
    "content": "A dream of love, so pure it seems,\nYour thoughts pull me back to stay,\nAnd wake me from my dream-filled way.\n\nReality isn’t like the dream,\nIt’s not as perfect, or so it seems.\nIn dreams, you do just what I want,\nBut in real life, it’s not the same front.\n\nFor dreams are where I see you true,\nThe only place I can be with you.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "when-i-am-lost-inside-a-dream",
    "categorySlug": "sad",
    "categoryName": "Sad",
    "likesCount": 72,
    "commentsCount": 27,
    "favoritesCount": 44,
    "viewsCount": 680,
    "sharesCount": 17,
    "downloadsCount": 14,
    "readingTime": 1,
    "tags": [
      "sad",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  },
  {
    "id": "poem-seed-14",
    "title": "When you are the  poem,",
    "subtitle": "A beautiful verse about friendship",
    "content": "I search for the meaning in every line,\nSome lines leave me mesmerized,\nDrawing me deeper into your mind.\n\nAs I read your words, a thought arises,\nI wish I could be the author of your poem,\nI start to believe you wrote it just for me,\nNot for others, but for my heart to see.\n\nFor when I hear the lines of your rhyme,\nMy heart melts with every word, every time.\n\nSOUL  AWAKENING\nI want to spend a lifetime with you,\nHold your hands forever, through every breath.\nYou're the only one I want to live for,\nWithout you, my life would come to an end.\n\nSeeing you awakens my soul,\nI'm drawn to you, my heart beats whole. I long to hold your hands and walk with you,\nGazing into your eyes, forever true.\n\nMy heart skips a beat when I see your face, Your eyes speak directly to my heart's. I promise to love you, now and forevermore,\nIn this life and the next, I'll adore.\n\nLet's walk together, hand in hand,\nForever entwined, in love's sweet plan.\nMy eyes meet your heart, and I pledge to stay,\nWith you, my love, every step of the way.\" LONGING  HEART\nYour eyes mesmerize me,\nYour voice is sweet music.\nI melt like a candle,\nMy heart beats fast.\n\nWhen I think of you, time flies, My heart whispers your name.\nI see your face in dreams,\nMy hands long to hold yours.\n\nYou drift away, leaving me with memories, But my heart refuses to forget.\nMy love remains true,\nA one-sided affection.\n\nI search for your eyes in crowds, Imagining us together.\nYou're the missing piece I need,\nLonging for our hearts to connect.\n\nUNSPOKEN  EMOTIONS\nWhen I look at you, I feel calm and at peace.\nYour smile completes the feeling, and my heart releases.\nYou fill a hole in my heart, a void I thought would stay.\nBut I know you don't feel the same, and that's hard to say.\n\nI crave your attention and love, a real touch.\nBut it's just a fantasy, and I fall back to reality's clutch.\nI hide my feelings because I know you don't feel the same.\nBut my heart holds on to the hope that one day you'll see my love and feel it too.\n\nSometimes I wonder what could be,\nIf only you saw me, and felt the same energy.\nBut until then, I'll hold on to this flame,\nAnd cherish the moments we share, even if it's just a game.\n\nIn dreams, I see us together, hand in hand,\nA love so strong, it shines like the sun in the sand.\nBut when I wake, reality sets in,\nAnd I'm left with just this longing, and a heart that can't give in.",
    "authorId": "admin-id",
    "authorName": "Prakash",
    "authorUsername": "prakash",
    "language": "en",
    "slug": "when-you-are-the--poem",
    "categorySlug": "friendship",
    "categoryName": "Friendship",
    "likesCount": 77,
    "commentsCount": 29,
    "favoritesCount": 47,
    "viewsCount": 725,
    "sharesCount": 18,
    "downloadsCount": 15,
    "readingTime": 4,
    "tags": [
      "friendship",
      "prakash",
      "siragii"
    ],
    "status": "published",
    "createdAt": "2026-08-09T10:00:00.000Z",
    "updatedAt": "2026-08-09T10:00:00.000Z",
    "category": "poem",
    "isPublished": true
  }
];

export const mockStories: Story[] = [
  {
    "id": "story-seed-1",
    "title": "The Silent Guardian",
    "subtitle": "A story about quiet courage in a bustling city.",
    "coverUrl": "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Drama",
    "content": "The streetlights flickered as midnight approached in the old quarter of Chennai. Arul walked through the quiet alleys, carrying a leather satchel filled with handwritten manuscripts. For years, he had been the anonymous storyteller of the neighborhood, leaving tales of hope on doorstep benches before sunrise.\n\nTonight was different. Tonight he was leaving his final chapter—a story dedicated to the girl who read his words under the balcony light every evening. As he placed the scroll on her windowsill, a soft voice whispered from behind the wooden blinds: \"I always knew it was you.\" Arul smiled in the shadows, knowing that some stories never end.",
    "createdAt": "2026-08-01T12:00:00.000Z",
    "updatedAt": "2026-08-01T12:00:00.000Z",
    "readingTime": 3,
    "tags": [
      "story",
      "romance",
      "chennai",
      "prakash"
    ],
    "status": "published",
    "likesCount": 45,
    "commentsCount": 12,
    "sharesCount": 18,
    "viewsCount": 350,
    "downloadsCount": 10,
    "isPublished": true
  },
  {
    "id": "story-seed-2",
    "title": "கனவுகளின் எல்லை",
    "subtitle": "சிறிய கிராமத்தில் வளர்ந்த ஒரு பெண்ணின் வெற்றிப் பயணம்.",
    "coverUrl": "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Inspirational",
    "content": "சூரியன் உதிக்கும் முன்பே நிலத்திற்குச் செல்லும் விவசாயியின் மகள் கவிதா. அவள் கைகளில் புத்தகங்களும், மனதளவில் ஆகாயத்தைத் தொடும் கனவுகளும் இருந்தன.\n\nகிராமத்து மனிதர்கள் அவளது முயற்சியைக் கண்டு சிரித்தார்கள். ஆனால் அவள் தன் நம்பிக்கையை இழக்கவில்லை. இரவுகளில் மண்ணெண்ணெய் விளக்கின் ஒளியில் படித்து, மாநிலத்தின் முதன்மைப் தேர்வில் தேர்ச்சி பெற்றாள். இன்று அவள் மாவட்ட ஆட்சியராகத் தன் சொந்தக் கிராமத்திற்குத் திரும்பியபோது, அன்று சிரித்த மனிதர்களே மலர் தூவி வரவேற்பளித்தார்கள்.",
    "createdAt": "2026-08-02T14:30:00.000Z",
    "updatedAt": "2026-08-02T14:30:00.000Z",
    "readingTime": 4,
    "tags": [
      "story",
      "tamil",
      "motivation",
      "prakash"
    ],
    "status": "published",
    "likesCount": 62,
    "commentsCount": 19,
    "sharesCount": 25,
    "viewsCount": 480,
    "downloadsCount": 14,
    "isPublished": true
  },
  {
    "id": "story-seed-3",
    "title": "The Unsent Letter",
    "subtitle": "A nostalgic story of friendship and time.",
    "coverUrl": "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "story",
    "genre": "Nostalgia",
    "content": "Inside an old wooden chest in the attic lay a yellowed envelope postmarked 2018. It had no stamp, only a name written in familiar fountain-pen ink. Karthik unfolded the page to find words he had written during his college days but never had the courage to mail.\n\n\"Distance can test us, but true memories remain unfaded.\" As he read his own teenage handwriting, his phone buzzed. It was a message from his college roommate after seven long years: \"Hey man, was just thinking about our hostel days.\" Some letters don't need postage to reach their destination.",
    "createdAt": "2026-08-03T09:15:00.000Z",
    "updatedAt": "2026-08-03T09:15:00.000Z",
    "readingTime": 2,
    "tags": [
      "story",
      "friendship",
      "nostalgia",
      "prakash"
    ],
    "status": "published",
    "likesCount": 38,
    "commentsCount": 8,
    "sharesCount": 14,
    "viewsCount": 290,
    "downloadsCount": 8,
    "isPublished": true
  }
];

export const mockQuotes: Quote[] = [
  {
    "id": "qte-prakash-1",
    "content": "Life is not easy...The hardest feeling is when you really want to talk to someone you love, but you can't.Sometimes, silence hurts more than words. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 15,
    "commentsCount": 2,
    "viewsCount": 110,
    "sharesCount": 4,
    "createdAt": "2026-08-02T00:24:59.964Z"
  },
  {
    "id": "qte-prakash-2",
    "content": "Something I wanted so badly before...is now just a memory.That memory still makes me smile.I have the strength to move on...but my heart doesn't. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 18,
    "commentsCount": 3,
    "viewsCount": 130,
    "sharesCount": 5,
    "createdAt": "2026-08-02T01:24:59.964Z"
  },
  {
    "id": "qte-prakash-3",
    "content": "When someone becomes very close to you...the biggest fear is losing them. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 21,
    "commentsCount": 4,
    "viewsCount": 150,
    "sharesCount": 6,
    "createdAt": "2026-08-02T02:24:59.966Z"
  },
  {
    "id": "qte-prakash-4",
    "content": "No one is too busy.If someone truly cares about you,they will always make time for you. ✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 24,
    "commentsCount": 5,
    "viewsCount": 170,
    "sharesCount": 7,
    "createdAt": "2026-08-02T03:24:59.966Z"
  },
  {
    "id": "qte-prakash-5",
    "content": "We don't know someone's value when they are with us.We understand it only after they leave. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Life",
    "tags": [
      "life",
      "prakash"
    ],
    "status": "published",
    "likesCount": 27,
    "commentsCount": 2,
    "viewsCount": 190,
    "sharesCount": 8,
    "createdAt": "2026-08-02T04:24:59.966Z"
  },
  {
    "id": "qte-prakash-6",
    "content": "Everything should have a limit.If we go beyond that limit,the same thing can become the reason for our biggest pain. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 30,
    "commentsCount": 3,
    "viewsCount": 210,
    "sharesCount": 4,
    "createdAt": "2026-08-02T05:24:59.966Z"
  },
  {
    "id": "qte-prakash-7",
    "content": "You can return something you don't like after buying it.But some decisions in life cannot be changed.So think before you decide. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 33,
    "commentsCount": 4,
    "viewsCount": 230,
    "sharesCount": 5,
    "createdAt": "2026-08-02T06:24:59.966Z"
  },
  {
    "id": "qte-prakash-8",
    "content": "Sometimes...after taking all the blame,we just want to disappear quietly from everyone's life. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 36,
    "commentsCount": 5,
    "viewsCount": 250,
    "sharesCount": 6,
    "createdAt": "2026-08-02T07:24:59.966Z"
  },
  {
    "id": "qte-prakash-9",
    "content": "Just because you love someone...doesn't mean they will love you back.Sometimes, love is one-sided. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 39,
    "commentsCount": 2,
    "viewsCount": 270,
    "sharesCount": 7,
    "createdAt": "2026-08-02T08:24:59.966Z"
  },
  {
    "id": "qte-prakash-10",
    "content": "Life doesn't always go the way we want.Sometimes we have to accept what happensand keep moving forward. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 42,
    "commentsCount": 3,
    "viewsCount": 290,
    "sharesCount": 8,
    "createdAt": "2026-08-02T09:24:59.967Z"
  },
  {
    "id": "qte-prakash-11",
    "content": "The things I love the most...always seem to go far away from me.It feels like nothing stays with me forever. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 45,
    "commentsCount": 4,
    "viewsCount": 310,
    "sharesCount": 4,
    "createdAt": "2026-08-02T10:24:59.967Z"
  },
  {
    "id": "qte-prakash-12",
    "content": "When someone you love leaves...it's not easy to forget them.They were a big part of your heart. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 48,
    "commentsCount": 5,
    "viewsCount": 330,
    "sharesCount": 5,
    "createdAt": "2026-08-02T11:24:59.967Z"
  },
  {
    "id": "qte-prakash-13",
    "content": "Leaving may be easy for us...but for someone who truly loves us,it can be very painful. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 51,
    "commentsCount": 2,
    "viewsCount": 350,
    "sharesCount": 6,
    "createdAt": "2026-08-02T12:24:59.967Z"
  },
  {
    "id": "qte-prakash-14",
    "content": "There comes a time...when nothing hurts anymore.Not because you're strong,but because your heart is already tired. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 54,
    "commentsCount": 3,
    "viewsCount": 370,
    "sharesCount": 7,
    "createdAt": "2026-08-02T13:24:59.967Z"
  },
  {
    "id": "qte-prakash-15",
    "content": "When the person you love is far away,you're scared something might happen to them.When they're with you,you're scared of losing them.That's what true love feels like. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 57,
    "commentsCount": 4,
    "viewsCount": 390,
    "sharesCount": 8,
    "createdAt": "2026-08-02T14:24:59.967Z"
  },
  {
    "id": "qte-prakash-16",
    "content": "If we're gone one day...people may miss us for some time.But slowly, life goes on.Everyone gets replaced one day. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 60,
    "commentsCount": 5,
    "viewsCount": 410,
    "sharesCount": 4,
    "createdAt": "2026-08-02T15:24:59.967Z"
  },
  {
    "id": "qte-prakash-17",
    "content": "When I stopped expecting too much from life...my heart felt a little lighter.I'm not fully happy,but I'm more peaceful now. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 63,
    "commentsCount": 2,
    "viewsCount": 430,
    "sharesCount": 5,
    "createdAt": "2026-08-02T16:24:59.967Z"
  },
  {
    "id": "qte-prakash-18",
    "content": "If you find someone better than me...don't stay with me because you feel bad.You deserve the best in life. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 66,
    "commentsCount": 3,
    "viewsCount": 450,
    "sharesCount": 6,
    "createdAt": "2026-08-02T17:24:59.967Z"
  },
  {
    "id": "qte-prakash-19",
    "content": "I want you to be the best photo in my camera. 📸🖤And I want to be the onewho captures that moment forever.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 69,
    "commentsCount": 4,
    "viewsCount": 470,
    "sharesCount": 7,
    "createdAt": "2026-08-02T18:24:59.967Z"
  },
  {
    "id": "qte-prakash-20",
    "content": "Don't think too much about everything.Life is already moving forward.Stay calm...and go with the flow. 🌙",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 72,
    "commentsCount": 5,
    "viewsCount": 490,
    "sharesCount": 8,
    "createdAt": "2026-08-02T19:24:59.967Z"
  },
  {
    "id": "qte-prakash-21",
    "content": "Something that means nothing to us...may be someone else's biggest dream.Life is all about how we see things. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 75,
    "commentsCount": 2,
    "viewsCount": 510,
    "sharesCount": 4,
    "createdAt": "2026-08-02T20:24:59.967Z"
  },
  {
    "id": "qte-prakash-22",
    "content": "The hardest feeling is...thinking that your absence doesn't matter to anyone.Sometimes, I even wonder...would anyone notice if I was gone? 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 78,
    "commentsCount": 3,
    "viewsCount": 530,
    "sharesCount": 5,
    "createdAt": "2026-08-02T21:24:59.967Z"
  },
  {
    "id": "qte-prakash-23",
    "content": "If you truly love someone...distance, pain, or silence can't change your feelings.Your heart will always look for them. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 81,
    "commentsCount": 4,
    "viewsCount": 550,
    "sharesCount": 6,
    "createdAt": "2026-08-02T22:24:59.967Z"
  },
  {
    "id": "qte-prakash-24",
    "content": "You can be surrounded by many people...and still feel lonely inside.Sometimes, that pain is worse than being alone. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 84,
    "commentsCount": 5,
    "viewsCount": 570,
    "sharesCount": 7,
    "createdAt": "2026-08-02T23:24:59.967Z"
  },
  {
    "id": "qte-prakash-25",
    "content": "In a world where everything is replaced...a person who tries to fix things instead of giving upis very rare. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 87,
    "commentsCount": 2,
    "viewsCount": 590,
    "sharesCount": 8,
    "createdAt": "2026-08-03T00:24:59.967Z"
  },
  {
    "id": "qte-prakash-26",
    "content": "We only know our side of the story.The other person may also be hiding a lot of pain.That's why many misunderstandings happen. 🖤",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Sad & Emotional",
    "tags": [
      "sad",
      "prakash"
    ],
    "status": "published",
    "likesCount": 90,
    "commentsCount": 3,
    "viewsCount": 610,
    "sharesCount": 4,
    "createdAt": "2026-08-03T01:24:59.967Z"
  },
  {
    "id": "qte-prakash-27",
    "content": "True friendship doesn't need daily conversations.Even if we don't talk every day,the bond stays the same. 🫂💗",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 93,
    "commentsCount": 4,
    "viewsCount": 630,
    "sharesCount": 5,
    "createdAt": "2026-08-03T02:24:59.967Z"
  },
  {
    "id": "qte-prakash-28",
    "content": "Sometimes...someone is quietly wishingto have just one conversation with you. 🌙One day, that wish may come true. ✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 96,
    "commentsCount": 5,
    "viewsCount": 650,
    "sharesCount": 6,
    "createdAt": "2026-08-03T03:24:59.967Z"
  },
  {
    "id": "qte-prakash-29",
    "content": "Maybe it took time...maybe it took distance...But life finally brought you together.And talking to them felt like everything was right again. 😊✨",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "thought",
    "genre": "Inspirational",
    "tags": [
      "inspirational",
      "prakash"
    ],
    "status": "published",
    "likesCount": 99,
    "commentsCount": 2,
    "viewsCount": 670,
    "sharesCount": 7,
    "createdAt": "2026-08-03T04:24:59.967Z"
  },
  {
    "id": "qte-prakash-30",
    "content": "Some things should be repaired, not replaced.Because memories, love, and emotionscan never be replaced by something new.",
    "author": "Prakash",
    "authorId": "admin-id",
    "authorUsername": "prakash",
    "category": "quote",
    "genre": "Love",
    "tags": [
      "love",
      "prakash"
    ],
    "status": "published",
    "likesCount": 102,
    "commentsCount": 3,
    "viewsCount": 690,
    "sharesCount": 8,
    "createdAt": "2026-08-03T05:24:59.967Z"
  }
];

export const mockComments: Comment[] = [];
export const mockCollections: Collection[] = [];
export const mockAudioTracks: AudioTrack[] = [];
export const mockAchievements: Achievement[] = [];
export const mockActivityLogs: ActivityLog[] = [];
export const mockTags: string[] = ['love', 'breakup', 'motivation', 'friendship', 'life', 'family', 'nature', 'emotional', 'inspirational', 'sad', 'festival', 'stories'];
